spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accounting
    username: root
    password: root
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        jdbc:
          batch_size: 10
          order_inserts: true
          cache:
            use_second_level_cache: false
        generate_statistics: true
    show-sql: false
    hibernate:
      ddl-auto: update
      format-sql: true
hibernate:
  id:
    optimizer:
      pooled:
        prefer_lo: true
